name: sponana
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - graphviz  # for Drake to render system diagrams
  - pip:
      - drake>=1.22.0
      - manipulation>=2023.11.0
      - jupyterlab